# Generated by Django 5.2.1 on 2025-05-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=255)),
                ('ln', models.CharField(max_length=255)),
                ('g', models.CharField(max_length=255)),
                ('em', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
            ],
        ),
    ]
